sed -i "s/ä/\&auml;/g" $1
sed -i "s/ö/\&ouml;/g" $1
sed -i "s/Ä/\&Auml;/g" $1
sed -i "s/Ö/\&Ouml;/g" $1
sed -i "s/å/\&aring;/g" $1
sed -i "s/Å/\&Aring;/g" $1
sed -i "s/é/\&eacute;/g" $1
sed -i "s/É/\&Eacute;/g" $1
sed -i "s/ø/\&oslash;/g" $1
sed -i "s/Ø/\&Oslash;/g" $1
sed -i "s/æ/\&aelig;/g" $1
sed -i "s/Æ/\&AElig;/g" $1
